version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/server
    tty: true
    stdin_open: true
    ports:
      - "8888:8888"
    environment:
      - PGHOST=db
      - PGDATABASE=koijan
      - PGUSER=root
      - PGPASSWORD=p@ssword
      - PGSSLMODE=disable
      - PGTZ=Asia/Tokyo
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - web
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "5173:5173"
    tty: true
    stdin_open: true
    networks:
      - web

  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=p@ssword
      - POSTGRES_DB=koijan
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - data-volume:/var/lib/postgresql/data
      - data-volume:/var/log
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - web
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "koijan"]
      interval: 5s
      timeout: 20s
      retries: 10

networks:
  web:

volumes:
  data-volume:
